## Mohammad Aliabadi 
## aliabadi4mohammad@gmail.com
## shahid beheshti university 

In [ ]:
# Exercise needs : 
  # one to many 
  # many to one 
  # تمرین مشخص نکرده که فیچر های ما یک بعدی یا چند بعدی باشن بنابراین هر دو شو انجام دادم

# what I did : 
  # one to one with one feature and two features!! solve it using 3 model : simple lstm and stacking and bidirctional 
  # one to many with one feature and two features and solve it usning 3 model : simple lstm and stacking and bidirectional
  # many to one with one featuer and two features and solve it using 3 model : simple lstm and stacking and bidirectional
  # many to many with one featuers and two features and solve it using 2 model : stacking and bidirectional 


In [ ]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.layers import Input
from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

# one to one 

In [ ]:
# create dataset 
# کلا 20 داده درست کردیم و اینکه هر لیبل 15 برابر داده ورودی هستش
X = list()
Y = list()
X = [x+1 for x in range(20)]
Y = [y * 15 for y in X]

print(X)
print(Y)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300]


In [ ]:
X = np.array(X)
Y = np.array(Y)

In [ ]:
# for lstm we use format of : (sample, time steps, features)
X = array(X).reshape(20, 1, 1)


# solve it with simple lstm

In [ ]:
# create our model with one lstm layer . 50 neuron and relu activation function 
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(1, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_2 (LSTM)               (None, 50)                10400     
                                                                 
 dense_2 (Dense)             (None, 1)                 51        
                                                                 
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
# train our model 
model.fit(X, Y, epochs=2000, validation_split=0.2, batch_size=5)


Epoch 1/2000
4/4 [==============================] - 2s 108ms/step - loss: 20942.7715 - val_loss: 76831.8359
Epoch 2/2000
4/4 [==============================] - 0s 16ms/step - loss: 20917.9180 - val_loss: 76735.6562
Epoch 3/2000
4/4 [==============================] - 0s 16ms/step - loss: 20895.2266 - val_loss: 76639.3281
Epoch 4/2000
4/4 [==============================] - 0s 19ms/step - loss: 20867.1895 - val_loss: 76542.5859
Epoch 5/2000
4/4 [==============================] - 0s 16ms/step - loss: 20842.6875 - val_loss: 76435.5000
Epoch 6/2000
4/4 [==============================] - 0s 17ms/step - loss: 20813.1855 - val_loss: 76320.9688
Epoch 7/2000
4/4 [==============================] - 0s 17ms/step - loss: 20784.0840 - val_loss: 76195.0938
Epoch 8/2000
4/4 [==============================] - 0s 18ms/step - loss: 20750.7949 - val_loss: 76063.1094
Epoch 9/2000
4/4 [==============================] - 0s 16ms/step - loss: 20721.0156 - val_loss: 75928.1875
Epoch 10/2000
4/4 [=================

In [ ]:
# test our model 

test_input = array([30])
test_input = test_input.reshape((1, 1, 1)) # convert to 3d shapeee
test_output = model.predict(test_input, verbose=0)
print(test_output)
# tru output : 450 but prediction is : 433.86    hmm not bad  :)

[[443.91672]]


## I solve it with stack lstm 

In [ ]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(1, 1)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 1, 50)             10400     
                                                                 
 lstm_4 (LSTM)               (None, 50)                20200     
                                                                 
 dense_3 (Dense)             (None, 1)                 51        
                                                                 
Total params: 30,651
Trainable params: 30,651
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
history = model.fit(X, Y, epochs=2000, validation_split=0.2, verbose=1, batch_size=5)


Epoch 1/2000
4/4 [==============================] - 3s 155ms/step - loss: 21034.5039 - val_loss: 77250.7188
Epoch 2/2000
4/4 [==============================] - 0s 23ms/step - loss: 21021.2793 - val_loss: 77206.9531
Epoch 3/2000
4/4 [==============================] - 0s 23ms/step - loss: 21010.8809 - val_loss: 77160.7188
Epoch 4/2000
4/4 [==============================] - 0s 30ms/step - loss: 20997.5938 - val_loss: 77108.4844
Epoch 5/2000
4/4 [==============================] - 0s 21ms/step - loss: 20984.0215 - val_loss: 77047.1953
Epoch 6/2000
4/4 [==============================] - 0s 22ms/step - loss: 20968.4160 - val_loss: 76978.0391
Epoch 7/2000
4/4 [==============================] - 0s 26ms/step - loss: 20950.8828 - val_loss: 76891.2109
Epoch 8/2000
4/4 [==============================] - 0s 23ms/step - loss: 20927.1094 - val_loss: 76784.0469
Epoch 9/2000
4/4 [==============================] - 0s 25ms/step - loss: 20897.9805 - val_loss: 76637.6641
Epoch 10/2000
4/4 [=================

In [ ]:
test_input = array([30])
test_input = test_input.reshape((1, 1, 1))
test_output = model.predict(test_input, verbose=0)
print(test_output)
# خب همونطور که میبینم نسبت به مدل قبلی ... خروجی بهتری بدست آوردیم

# I will use 2 features for one to one 




In [ ]:
# create dataset 
# در این جا برای ساخت دیتاست از دو فیچر استفاده کردم و لیبل رو گذاشتم ضرب دو فیچر برای هر تایم استپ
nums = 25

X1 = list()
X2 = list()
X = list()
Y = list()

X1 = [(x+1)*2 for x in range(25)]
X2 = [(x+1)*3 for x in range(25)]
Y = [x1*x2 for x1,x2 in zip(X1,X2)]

print(X1)
print(X2)
print(Y)

In [ ]:
X = np.column_stack((X1, X2))
print(X)

In [ ]:
X = array(X).reshape(25, 1, 2)


## i will solve 2 features with simple lstm 

In [ ]:
model = Sequential()
model.add(LSTM(80, activation='relu', input_shape=(1, 2)))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

In [ ]:
model.fit(X, Y, epochs=2000, validation_split=0.2, batch_size=5)


In [ ]:
test_input = array([55,80])  # hmmmm actual ouput is 55*88 = 4400
test_input = test_input.reshape((1, 1, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output) # مقدرای که پیش بینی کرد خیلی از مقدار واقعی دور هست :/

# I will solve it with stack lstm 

In [ ]:
model = Sequential()
model.add(LSTM(200, activation='relu', return_sequences=True, input_shape=(1, 2)))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(LSTM(50, activation='relu', return_sequences=True))
model.add(LSTM(25, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

In [ ]:
# چون مدل پیچیده تر شد مجبور شدم تعداد ایپوک ها رو کاهش بدم 
history = model.fit(X, Y, epochs=1000, validation_split=0.1, verbose=1, batch_size=3)

test_output = model.predict(test_input, verbose=0)
print(test_output) # همنوطر که میبینم خروجی ای  که اینجا بدست اومده از مدل ساده خیلی بهتره

In [ ]:
# نتیجه ای که گرفتم این بود که در هر دو حالت تک فیچر و دو فیچر ... دقت استک خیلی بهتر از مدل ساده بود 


15/12/2021

# many to one with simple lstm

In [ ]:
# پانزده داده تولید کردم که هر کدوم 3 تا تایم استپ دارن و لیبل هم مجموع این 3 مقدار هست
# فعلا هم از حالت تک فیچره استفاده کردم 

X = np.array([x+1 for x in range(45)])
print(X)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]


In [ ]:
X = X.reshape(15,3,1)
print(X)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]

 [[16]
  [17]
  [18]]

 [[19]
  [20]
  [21]]

 [[22]
  [23]
  [24]]

 [[25]
  [26]
  [27]]

 [[28]
  [29]
  [30]]

 [[31]
  [32]
  [33]]

 [[34]
  [35]
  [36]]

 [[37]
  [38]
  [39]]

 [[40]
  [41]
  [42]]

 [[43]
  [44]
  [45]]]


In [ ]:
Y = list()
for x in X:
    Y.append(x.sum())

Y = np.array(Y)
print(Y)

[  6  15  24  33  42  51  60  69  78  87  96 105 114 123 132]


## solve it with pure lsm 

In [ ]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(3, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [ ]:
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1)

Epoch 1/1000
1/1 [==============================] - 2s 2s/step - loss: 4330.0366 - val_loss: 16306.3203
Epoch 2/1000
1/1 [==============================] - 0s 42ms/step - loss: 4286.5142 - val_loss: 16142.4453
Epoch 3/1000
1/1 [==============================] - 0s 40ms/step - loss: 4242.5200 - val_loss: 15976.7764
Epoch 4/1000
1/1 [==============================] - 0s 44ms/step - loss: 4197.9731 - val_loss: 15808.9688
Epoch 5/1000
1/1 [==============================] - 0s 39ms/step - loss: 4152.7793 - val_loss: 15638.8594
Epoch 6/1000
1/1 [==============================] - 0s 42ms/step - loss: 4106.8379 - val_loss: 15469.8506
Epoch 7/1000
1/1 [==============================] - 0s 50ms/step - loss: 4060.4775 - val_loss: 15302.7891
Epoch 8/1000
1/1 [==============================] - 0s 49ms/step - loss: 4014.2305 - val_loss: 15133.6914
Epoch 9/1000
1/1 [==============================] - 0s 41ms/step - loss: 3967.9473 - val_loss: 14958.8428
Epoch 10/1000
1/1 [=============================

In [ ]:
test_input = array([50,51,52]) # 50 + 51 + 52 = 153 
test_input = test_input.reshape((1, 3, 1))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[152.90726]]


# I choose stack lstm 

In [ ]:
model = Sequential()
model.add(LSTM(200, activation='relu', return_sequences=True, input_shape=(3, 1)))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(LSTM(50, activation='relu', return_sequences=True))
model.add(LSTM(25, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1)

Epoch 1/1000
1/1 [==============================] - 6s 6s/step - loss: 4045.5364 - val_loss: 15180.7266
Epoch 2/1000
1/1 [==============================] - 0s 81ms/step - loss: 4044.7898 - val_loss: 15177.5938
Epoch 3/1000
1/1 [==============================] - 0s 84ms/step - loss: 4043.7590 - val_loss: 15173.8213
Epoch 4/1000
1/1 [==============================] - 0s 88ms/step - loss: 4042.5000 - val_loss: 15169.1016
Epoch 5/1000
1/1 [==============================] - 0s 84ms/step - loss: 4040.9922 - val_loss: 15163.6250
Epoch 6/1000
1/1 [==============================] - 0s 84ms/step - loss: 4039.2712 - val_loss: 15156.2100
Epoch 7/1000
1/1 [==============================] - 0s 95ms/step - loss: 4037.1985 - val_loss: 15145.2764
Epoch 8/1000
1/1 [==============================] - 0s 82ms/step - loss: 4034.5398 - val_loss: 15129.9453
Epoch 9/1000
1/1 [==============================] - 0s 83ms/step - loss: 4031.1453 - val_loss: 15108.7861
Epoch 10/1000
1/1 [=============================

In [ ]:
test_output = model.predict(test_input, verbose=0)
print(test_output) # مقدار بهتری رو نسبت به مدل قبلی پیش بینی کرد 

# many to one with bidirectional lstm 

In [ ]:
from keras.layers import Bidirectional

model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(3, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [ ]:
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1)
test_output = model.predict(test_input, verbose=0)
print(test_output)

Epoch 1/1000
1/1 [==============================] - 3s 3s/step - loss: 3973.4043 - val_loss: 14741.0049
Epoch 2/1000
1/1 [==============================] - 0s 38ms/step - loss: 3935.4797 - val_loss: 14606.2783
Epoch 3/1000
1/1 [==============================] - 0s 36ms/step - loss: 3897.0996 - val_loss: 14469.1357
Epoch 4/1000
1/1 [==============================] - 0s 38ms/step - loss: 3858.1301 - val_loss: 14328.5156
Epoch 5/1000
1/1 [==============================] - 0s 41ms/step - loss: 3818.3816 - val_loss: 14183.1992
Epoch 6/1000
1/1 [==============================] - 0s 42ms/step - loss: 3777.6443 - val_loss: 14031.9961
Epoch 7/1000
1/1 [==============================] - 0s 36ms/step - loss: 3735.7207 - val_loss: 13873.6328
Epoch 8/1000
1/1 [==============================] - 0s 32ms/step - loss: 3692.3816 - val_loss: 13706.8721
Epoch 9/1000
1/1 [==============================] - 0s 31ms/step - loss: 3647.3503 - val_loss: 13530.3359
Epoch 10/1000
1/1 [=============================

# many to one with 2 features

In [ ]:
X1 = np.array([x+3 for x in range(0, 135, 3)])
print(X1)

X2 = np.array([x+5 for x in range(0, 225, 5)])
print(X2)

[  3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51  54
  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105 108
 111 114 117 120 123 126 129 132 135]
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200 205 210 215 220 225]


In [ ]:
X = np.column_stack((X1, X2))
print(X)

[[  3   5]
 [  6  10]
 [  9  15]
 [ 12  20]
 [ 15  25]
 [ 18  30]
 [ 21  35]
 [ 24  40]
 [ 27  45]
 [ 30  50]
 [ 33  55]
 [ 36  60]
 [ 39  65]
 [ 42  70]
 [ 45  75]
 [ 48  80]
 [ 51  85]
 [ 54  90]
 [ 57  95]
 [ 60 100]
 [ 63 105]
 [ 66 110]
 [ 69 115]
 [ 72 120]
 [ 75 125]
 [ 78 130]
 [ 81 135]
 [ 84 140]
 [ 87 145]
 [ 90 150]
 [ 93 155]
 [ 96 160]
 [ 99 165]
 [102 170]
 [105 175]
 [108 180]
 [111 185]
 [114 190]
 [117 195]
 [120 200]
 [123 205]
 [126 210]
 [129 215]
 [132 220]
 [135 225]]


In [ ]:
X = array(X).reshape(15, 3, 2)
print(X)

[[[  3   5]
  [  6  10]
  [  9  15]]

 [[ 12  20]
  [ 15  25]
  [ 18  30]]

 [[ 21  35]
  [ 24  40]
  [ 27  45]]

 [[ 30  50]
  [ 33  55]
  [ 36  60]]

 [[ 39  65]
  [ 42  70]
  [ 45  75]]

 [[ 48  80]
  [ 51  85]
  [ 54  90]]

 [[ 57  95]
  [ 60 100]
  [ 63 105]]

 [[ 66 110]
  [ 69 115]
  [ 72 120]]

 [[ 75 125]
  [ 78 130]
  [ 81 135]]

 [[ 84 140]
  [ 87 145]
  [ 90 150]]

 [[ 93 155]
  [ 96 160]
  [ 99 165]]

 [[102 170]
  [105 175]
  [108 180]]

 [[111 185]
  [114 190]
  [117 195]]

 [[120 200]
  [123 205]
  [126 210]]

 [[129 215]
  [132 220]
  [135 225]]]


##  1. solve it with simple lstm 
---

In [ ]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(3, 2)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1)

Epoch 1/1000
1/1 [==============================] - 2s 2s/step - loss: 4243.3276 - val_loss: 15699.5234
Epoch 2/1000
1/1 [==============================] - 0s 38ms/step - loss: 4143.0317 - val_loss: 15494.1562
Epoch 3/1000
1/1 [==============================] - 0s 30ms/step - loss: 4056.9661 - val_loss: 15222.8721
Epoch 4/1000
1/1 [==============================] - 0s 35ms/step - loss: 3968.0413 - val_loss: 14915.0625
Epoch 5/1000
1/1 [==============================] - 0s 58ms/step - loss: 3871.7571 - val_loss: 14585.4834
Epoch 6/1000
1/1 [==============================] - 0s 37ms/step - loss: 3768.8779 - val_loss: 14244.4609
Epoch 7/1000
1/1 [==============================] - 0s 40ms/step - loss: 3660.1619 - val_loss: 13889.4717
Epoch 8/1000
1/1 [==============================] - 0s 35ms/step - loss: 3545.3447 - val_loss: 13484.8936
Epoch 9/1000
1/1 [==============================] - 0s 37ms/step - loss: 3418.9778 - val_loss: 12933.4990
Epoch 10/1000
1/1 [=============================

In [ ]:
test_input = array([[8, 51],
                    [11,56],
                    [14,61]])  # 14+61 = 75 : actual output 

test_input = test_input.reshape((1, 3, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[35.902912]]


##  2. solve it with stack lstm

---



In [ ]:
model = Sequential()
model.add(LSTM(200, activation='relu', return_sequences=True, input_shape=(3, 2)))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(LSTM(50, activation='relu', return_sequences=True))
model.add(LSTM(25, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1)

test_output = model.predict(test_input, verbose=0)
print(test_output) # نیتجه خیلی بدتر از مدل قبلی بود . بنظر میرسه که مدل اورفیت کرده باشه

# using bidirectional

In [ ]:
from keras.layers import Bidirectional

model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(3, 2)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1)
test_output = model.predict(test_input, verbose=0)
print(test_output)

# one to many 


In [ ]:
# پانزده دیتا رو تولید میکنیم و لیبل رو اینطوری میزنیم که به ازای هر ورودی ... مدل باید دو عدد بعدیشو در دستگاه اعداد صحیح به ما بده 
# یعنی اگر 4 رو بدیم باید 5 و 6 رو به عنوان خروجی به ما بده 

X = list()
Y = list()
X = [x+3 for x in range(-2, 43, 3)]

for i in X:
    output_vector = list()
    output_vector.append(i+1)
    output_vector.append(i+2)
    Y.append(output_vector)

print(X)
print(Y)

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43]
[[2, 3], [5, 6], [8, 9], [11, 12], [14, 15], [17, 18], [20, 21], [23, 24], [26, 27], [29, 30], [32, 33], [35, 36], [38, 39], [41, 42], [44, 45]]


In [ ]:
X = np.array(X).reshape(15, 1, 1)
Y = np.array(Y)

# solve it using simple lstm 

In [ ]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(1, 1)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
model.fit(X, Y, epochs=1000, validation_split=0.2, batch_size=3)

Epoch 1/1000
4/4 [==============================] - 3s 100ms/step - loss: 451.7522 - val_loss: 1635.1332
Epoch 2/1000
4/4 [==============================] - 0s 11ms/step - loss: 445.2060 - val_loss: 1615.0581
Epoch 3/1000
4/4 [==============================] - 0s 11ms/step - loss: 440.6533 - val_loss: 1593.6517
Epoch 4/1000
4/4 [==============================] - 0s 13ms/step - loss: 434.5598 - val_loss: 1572.3988
Epoch 5/1000
4/4 [==============================] - 0s 12ms/step - loss: 428.9380 - val_loss: 1550.5895
Epoch 6/1000
4/4 [==============================] - 0s 10ms/step - loss: 423.6000 - val_loss: 1527.8402
Epoch 7/1000
4/4 [==============================] - 0s 10ms/step - loss: 417.2123 - val_loss: 1504.7643
Epoch 8/1000
4/4 [==============================] - 0s 11ms/step - loss: 412.0081 - val_loss: 1479.6631
Epoch 9/1000
4/4 [==============================] - 0s 11ms/step - loss: 404.7420 - val_loss: 1454.2896
Epoch 10/1000
4/4 [==============================] - 0s 18ms/st

In [ ]:
test_input = array([10])
test_input = test_input.reshape((1, 1, 1))
test_output = model.predict(test_input, verbose=0)
print(test_output)

SyntaxError: ignored

# solve it with stacking

In [ ]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(1, 1)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)

test_output = model.predict(test_input, verbose=0)
print(test_output)

# solve it using bidirectional lstm 

In [ ]:
from keras.layers import Bidirectional

model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(1, 1)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)
test_output = model.predict(test_input, verbose=0)
print(test_output)

# one to many using 2 feautres 

In [ ]:
nums = 25

X1 = list()
X2 = list()
X = list()
Y = list()

X1 = [(x+1)*2 for x in range(25)]
X2 = [(x+1)*3 for x in range(25)]

for x1, x2 in zip(X1, X2):
    output_vector = list()
    output_vector.append(x1+1)
    output_vector.append(x2+1)
    Y.append(output_vector)

X = np.column_stack((X1, X2))
print(X)

In [ ]:
X = np.array(X).reshape(25, 1, 2)
Y = np.array(Y)

# solve it with simple lstm 

In [ ]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(1, 2)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
model.fit(X, Y, epochs=1000, validation_split=0.2, batch_size=3)

In [ ]:
test_input = array([40, 60])
test_input = test_input.reshape((1, 1, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output)

# solve it using stacking 

In [ ]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(1, 2)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)

test_input = array([40, 60])
test_input = test_input.reshape((1, 1, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output)

# solve it using bidirectional 

In [ ]:
from keras.layers import Bidirectional

model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(1, 2)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)
test_output = model.predict(test_input, verbose=0)
print(test_output)

# many to many 

In [ ]:
# I'm tired :(

In [ ]:
X = list()
Y = list()
X = [x for x in range(5, 301, 5)]
Y = [y for y in range(20, 316, 5)]

X = np.array(X).reshape(20, 3, 1)
Y = np.array(Y).reshape(20, 3, 1)

# solve it using stacking 

In [ ]:
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

model = Sequential()

# encoder layer
model.add(LSTM(100, activation='relu', input_shape=(3, 1)))

# repeat vector
model.add(RepeatVector(3))

# decoder layer
model.add(LSTM(100, activation='relu', return_sequences=True))

model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')

print(model.summary())

In [ ]:
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)


In [ ]:
test_input = array([300, 305, 310])
test_input = test_input.reshape((1, 3, 1))
test_output = model.predict(test_input, verbose=0)
print(test_output)

# solve it using bidirectinoal 

In [ ]:
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

model = Sequential()
model.add(Bidirectional(LSTM(100, activation='relu', input_shape=(3, 1))))
model.add(RepeatVector(3))
model.add(Bidirectional(LSTM(100, activation='relu', return_sequences=True)))
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)

In [ ]:
test_output = model.predict(test_input, verbose=0)
print(test_output)

with 2 features 

In [ ]:
X = list()
Y = list()
X1 = [x1 for x1 in range(5, 301, 5)]
X2 = [x2 for x2 in range(20, 316, 5)]
Y = [y for y in range(35, 331, 5)]

X = np.column_stack((X1, X2))

In [ ]:
X = np.array(X).reshape(20, 3, 2)
Y = np.array(Y).reshape(20, 3, 1)

# solve it using stacking 

In [ ]:
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(3, 2)))
model.add(RepeatVector(3))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)

In [ ]:
X1 = [300, 305, 310]
X2 = [315, 320, 325]

test_input = np.column_stack((X1, X2))

test_input = test_input.reshape((1, 3, 2))
print(test_input)

In [ ]:
test_output = model.predict(test_input, verbose=0)
print(test_output)

# solve it using bidirectional 

In [ ]:
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

model = Sequential()
model.add(Bidirectional(LSTM(100, activation='relu', input_shape=(3, 2))))
model.add(RepeatVector(3))
model.add(Bidirectional(LSTM(100, activation='relu', return_sequences=True)))
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)

In [ ]:
test_output = model.predict(test_input, verbose=0)
print(test_output)